services:
  webmin:
    image: debian:jessie
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/games:/usr/local/games
      - LC_ALL=C.UTF-8
    command:
      - apt-get update
      - apt-get install -y wget locales
      - dpkg-reconfigure locales
      - locale-gen C.UTF-8
      - /usr/sbin/update-locale LANG=C.UTF-8
      - wget http://www.webmin.com/jcameron-key.asc
      - apt-key add jcameron-key.asc
      - echo "deb http://download.webmin.com/download/repository sarge contrib" >> /etc/apt/sources.list
      - echo "deb http://webmin.mirror.somersettechsolutions.co.uk/repository sarge contrib" >> /etc/apt/sources.list
      - apt-get update
      - apt-get install -y webmin
      - apt-get clean
      - /usr/bin/touch /var/webmin/miniserv.log
      - /usr/sbin/service webmin restart
      - /usr/bin/tail -f /var/webmin/miniserv.log
    ports:
      - 10000:10000
    volumes:
      - adata:/etc/webmin
    restart: never

volumes:
  adata:
